name: Release integrations manager
on:
  release:
    types: [ released ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build resources
        run: |
          make build
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'library/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}