name: Release translator
on:
  release:
    types: [ released ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-12]
    steps:
      - uses: actions/checkout@master
      - name: Build resources
        run: |
          make build
      - name: Rename binary
        run: |
          mv library/translator.so library/translator-${{ matrix.os }}.so 
          mv library/translator.h library/translator-${{ matrix.os }}.h 
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: library/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true