name: Release translator
on:
  release:
    types: [ released ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build resources
        run: |
          make build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: library/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true