name: Test 
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ '1.18']
    name: Go ${{ matrix.version }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}
      - uses: actions/checkout@v2
      - name: Execute test in integrations manager
        run: |
          go mod tidy
          go mod download
          go test ./...